name: Deploy to server with Telegram notifications

on:
  push:
    branches: ["*"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SSH - Prepare and Pull Code
      uses: appleboy/ssh-action@v1.0.0
      id: prepare
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 8542
        command_timeout: 20m
        script: |
          echo "== [1] Перехожу в директорию проекта =="
          cd ~/Desktop/library || exit 1

          echo "== [2] Проверка и сброс локальных изменений =="
          if [ -n "$(git status --porcelain)" ]; then
            echo "→ Обнаружены изменения, сбрасываю..."
            git reset --hard HEAD
            git clean -fd
          fi

          echo "== [3] Обновление кода из репозитория =="
          git pull

    - name: SSH - Stop Previous Containers
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 8542
        command_timeout: 10m
        script: |
          echo "== [4] Останавливаю старые контейнеры =="
          cd ~/Desktop/library || exit 1
          docker-compose down

    - name: SSH - Build and Start
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 8542
        command_timeout: 20m
        script: |
          echo "== [5] Собираю и запускаю контейнеры =="
          cd ~/Desktop/library || exit 1
          docker-compose build
          docker-compose up -d

          echo "== [6] Последние 100 строк логов =="
          docker-compose logs --tail=100

    - name: Send Telegram notification (Success)
      if: success()
      uses: appleboy/telegram-action@v1.0.0
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          ✅ Деплой успешен!
          Репозиторий: ${{ github.repository }}
          Ветка: ${{ github.ref }}
          Сервер: ${{ secrets.SSH_HOST }}
          Запустил: ${{ github.actor }}

          🔗 http://5.129.199.10:8777/docs

          Для логов: `docker-compose logs -f`

    - name: Send Telegram notification (Failure)
      if: failure()
      uses: appleboy/telegram-action@v1.0.0
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          ❌ Деплой упал!
          Репозиторий: ${{ github.repository }}
          Ветка: ${{ github.ref }}
          Ошибка в шаге: ${{ steps.prepare.outcome }}
          Подробнее: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
